POST http://localhost:5000/userTask/createUserTask
Content-Type: application/json

{
    "myTaskTitle":"learn and grow",
    "myTaskDescription":"learning is very important"
}


###
POST https://obscure-earth-47353.herokuapp.com/userTask/createUserTask
Content-Type: application/json

{
    "myTaskTitle":"learn and grow",
    "myTaskDescription":"learning is very important"
}




GET http://localhost:5000/userTask/getUserTask
 